steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - strava-stats-fetcher
  - --region=europe-central2
  - --source=.
  - --runtime=python39
  - --project=impressive-hall-298918
options:
  logging: CLOUD_LOGGING_ONLY